[package]
name = "pipetext-rs"
version = "0.1.0"
authors = ["Ethan Spurlock <ethan@spurlock.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
lipschitz-rs = { path = "C:\\Users\\Ethan\\Desktop\\lipschitz-rs" }
